

[
  {
    "active": true,
    "classNameId": 9,
    "classPK": 66748356,
    "companyId": 1,
    "creatorUserId": 66748356,
    "description": "",
    "friendlyURL": "\/allen.ziegenfus",
    "groupId": 66748362,
    "liveGroupId": 0,
    "name": "66748356",
    "parentGroupId": 0,
    "site": false,
    "type": 0,
    "typeSettings": ""
  },
  {
    "active": true,
    "classNameId": 10008,
    "classPK": 47511581,
    "companyId": 1,
    "creatorUserId": 1395288,
    "description": "",
    "friendlyURL": "\/france2015",
    "groupId": 47511581,
    "liveGroupId": 0,
    "name": "Conference - Symposium - France 2015",
    "parentGroupId": 0,
    "site": true,
    "type": 3,
    "typeSettings": "mergeGuestPublicPages=false\n"
  },
  {
    "active": true,
    "classNameId": 10008,
    "classPK": 3133562,
    "companyId": 1,
    "creatorUserId": 11189,
    "description": "",
    "friendlyURL": "\/customer",
    "groupId": 3133562,
    "liveGroupId": 0,
    "name": "Customer Portal",
    "parentGroupId": 0,
    "site": true,
    "type": 3,
    "typeSettings": "mergeGuestPublicPages=false\n"
  },
  {
    "active": true,
    "classNameId": 10008,
    "classPK": 326305,
    "companyId": 1,
    "creatorUserId": 11054,
    "description": "Internal community for all things related to our Employee Volunteer Plan (EVP)",
    "friendlyURL": "\/evp",
    "groupId": 326305,
    "liveGroupId": 0,
    "name": "Employee Volunteer Plan",
    "parentGroupId": 0,
    "site": true,
    "type": 3,
    "typeSettings": "mergeGuestPublicPages=false\n"
  },
  {
    "active": true,
    "classNameId": 10008,
    "classPK": 47511614,
    "companyId": 1,
    "creatorUserId": 1395288,
    "description": "",
    "friendlyURL": "\/events2015",	
    "groupId": 47511614,
    "liveGroupId": 0,
    "name": "Events 2015",
    "parentGroupId": 0,
    "site": true,
    "type": 3,
    "typeSettings": "mergeGuestPublicPages=false\n"
  },
  {
    "active": true,
    "classNameId": 10008,
    "classPK": 67510365,
    "companyId": 1,
    "creatorUserId": 167904,
    "description": "",
    "friendlyURL": "\/events2016",
    "groupId": 67510365,
    "liveGroupId": 0,
    "name": "Events 2016",
    "parentGroupId": 0,
    "site": true,
    "type": 3,
    "typeSettings": "mergeGuestPublicPages=false\n"
  },
  {
    "active": true,
    "classNameId": 10008,
    "classPK": 14,
    "companyId": 1,
    "creatorUserId": 5,
    "description": "",
    "friendlyURL": "\/guest",
    "groupId": 14,
    "liveGroupId": 0,
    "name": "Guest",
    "parentGroupId": 0,
    "site": true,
    "type": 3,
    "typeSettings": "false-robots.txt=User-Agent: *_SAFE_NEWLINE_CHARACTER_Disallow:_SAFE_NEWLINE_CHARACTER_Disallow: \/*get_file?_SAFE_NEWLINE_CHARACTER_Disallow: \/documents\/_SAFE_NEWLINE_CHARACTER_Sitemap: http:\/\/www.liferay.com\/sitemap.xml\nmergeGuestPublicPages=false\n"
  },
  {
    "active": true,
    "classNameId": 10008,
    "classPK": 35935974,
    "companyId": 1,
    "creatorUserId": 1395288,
    "description": "",
    "friendlyURL": "\/changeforlife",
    "groupId": 35935974,
    "liveGroupId": 0,
    "name": "Liferay Change For Life",
    "parentGroupId": 0,
    "site": true,
    "type": 3,
    "typeSettings": "mergeGuestPublicPages=false\n"
  },
  {
    "active": true,
    "classNameId": 10008,
    "classPK": 136812,
    "companyId": 1,
    "creatorUserId": 2,
    "description": "",
    "friendlyURL": "\/employees",
    "groupId": 136812,
    "liveGroupId": 0,
    "name": "Liferay Employees",
    "parentGroupId": 0,
    "site": true,
    "type": 3,
    "typeSettings": ""
  },
  {
    "active": true,
    "classNameId": 10008,
    "classPK": 296326,
    "companyId": 1,
    "creatorUserId": 11127,
    "description": "",
    "friendlyURL": "\/sales",
    "groupId": 296326,
    "liveGroupId": 0,
    "name": "Liferay Sales",
    "parentGroupId": 0,
    "site": true,
    "type": 3,
    "typeSettings": "workflowEnabled=false\n"
  },
  {
    "active": true,
    "classNameId": 10008,
    "classPK": 547572,
    "companyId": 1,
    "creatorUserId": 11174,
    "description": "",
    "friendlyURL": "\/liferaysupport",
    "groupId": 547572,
    "liveGroupId": 0,
    "name": "Liferay Support",
    "parentGroupId": 0,
    "site": true,
    "type": 3,
    "typeSettings": ""
  },
  {
    "active": true,
    "classNameId": 10008,
    "classPK": 668602,
    "companyId": 1,
    "creatorUserId": 11154,
    "description": "",
    "friendlyURL": "\/training",
    "groupId": 668602,
    "liveGroupId": 0,
    "name": "Liferay University",
    "parentGroupId": 0,
    "site": true,
    "type": 3,
    "typeSettings": "mergeGuestPublicPages=false\n"
  },
  {
    "active": true,
    "classNameId": 8,
    "classPK": 21,
    "companyId": 1,
    "creatorUserId": 5,
    "description": "",
    "friendlyURL": "\/21",
    "groupId": 22,
    "liveGroupId": 0,
    "name": "Liferay, Inc. LFR_ORGANIZATION",
    "parentGroupId": 0,
    "site": true,
    "type": 3,
    "typeSettings": ""
  },
  {
    "active": true,
    "classNameId": 10008,
    "classPK": 33392425,
    "companyId": 1,
    "creatorUserId": 1395288,
    "description": "",
    "friendlyURL": "\/developer",
    "groupId": 33392425,
    "liveGroupId": 0,
    "name": "Marketplace Developer Portal",
    "parentGroupId": 0,
    "site": true,
    "type": 3,
    "typeSettings": "mergeGuestPublicPages=false\n"
  },
  {
    "active": true,
    "classNameId": 10008,
    "classPK": 3022218,
    "companyId": 1,
    "creatorUserId": 10437,
    "description": "",
    "friendlyURL": "\/partner",
    "groupId": 3022218,
    "liveGroupId": 0,
    "name": "Partner Portal",
    "parentGroupId": 0,
    "site": true,
    "type": 2,
    "typeSettings": "mergeGuestPublicPages=false\n"
  }
]

